{"message":"database error => MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]\n    at Pool.<anonymous> (/Users/why/学习/Dian/大创项目/攻防实验系统/HUST_Info_Security_platform/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:159:13)\n    at Connection.<anonymous> (/Users/why/学习/Dian/大创项目/攻防实验系统/HUST_Info_Security_platform/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:254:19)\n    at Connection.emit (events.js:159:13)\n    at Socket.<anonymous> (/Users/why/学习/Dian/大创项目/攻防实验系统/HUST_Info_Security_platform/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:254:19)\n    at Socket.emit (events.js:159:13)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at process._tickCallback (internal/process/next_tick.js:152:19)","level":"error"}
